//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.FlightHotelServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Flight", Namespace="http://schemas.datacontract.org/2004/07/FlightHotel")]
    [System.SerializableAttribute()]
    public partial class Flight : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GUI.FlightHotelServiceReference.LegDetails[] FlightDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GUI.FlightHotelServiceReference.LegDetails[] FlightDetails {
            get {
                return this.FlightDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightDetailsField, value) != true)) {
                    this.FlightDetailsField = value;
                    this.RaisePropertyChanged("FlightDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalPriceField, value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LegDetails", Namespace="http://schemas.datacontract.org/2004/07/FlightHotel")]
    [System.SerializableAttribute()]
    public partial class LegDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DstTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FlightNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SrcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SrcTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dst {
            get {
                return this.DstField;
            }
            set {
                if ((object.ReferenceEquals(this.DstField, value) != true)) {
                    this.DstField = value;
                    this.RaisePropertyChanged("Dst");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DstTime {
            get {
                return this.DstTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DstTimeField, value) != true)) {
                    this.DstTimeField = value;
                    this.RaisePropertyChanged("DstTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FlightNumber {
            get {
                return this.FlightNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FlightNumberField, value) != true)) {
                    this.FlightNumberField = value;
                    this.RaisePropertyChanged("FlightNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Src {
            get {
                return this.SrcField;
            }
            set {
                if ((object.ReferenceEquals(this.SrcField, value) != true)) {
                    this.SrcField = value;
                    this.RaisePropertyChanged("Src");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SrcTime {
            get {
                return this.SrcTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.SrcTimeField, value) != true)) {
                    this.SrcTimeField = value;
                    this.RaisePropertyChanged("SrcTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotel", Namespace="http://schemas.datacontract.org/2004/07/FlightHotel")]
    [System.SerializableAttribute()]
    public partial class Hotel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RatingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingField, value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FlightHotelServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFlights", ReplyAction="http://tempuri.org/IService1/GetFlightsResponse")]
        GUI.FlightHotelServiceReference.Flight[] GetFlights(string Origin, string Destination, string Date, int Adults, string Cabin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFlights", ReplyAction="http://tempuri.org/IService1/GetFlightsResponse")]
        System.Threading.Tasks.Task<GUI.FlightHotelServiceReference.Flight[]> GetFlightsAsync(string Origin, string Destination, string Date, int Adults, string Cabin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNearbyHotels", ReplyAction="http://tempuri.org/IService1/GetNearbyHotelsResponse")]
        GUI.FlightHotelServiceReference.Hotel[] GetNearbyHotels(string Location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetNearbyHotels", ReplyAction="http://tempuri.org/IService1/GetNearbyHotelsResponse")]
        System.Threading.Tasks.Task<GUI.FlightHotelServiceReference.Hotel[]> GetNearbyHotelsAsync(string Location);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : GUI.FlightHotelServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<GUI.FlightHotelServiceReference.IService1>, GUI.FlightHotelServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GUI.FlightHotelServiceReference.Flight[] GetFlights(string Origin, string Destination, string Date, int Adults, string Cabin) {
            return base.Channel.GetFlights(Origin, Destination, Date, Adults, Cabin);
        }
        
        public System.Threading.Tasks.Task<GUI.FlightHotelServiceReference.Flight[]> GetFlightsAsync(string Origin, string Destination, string Date, int Adults, string Cabin) {
            return base.Channel.GetFlightsAsync(Origin, Destination, Date, Adults, Cabin);
        }
        
        public GUI.FlightHotelServiceReference.Hotel[] GetNearbyHotels(string Location) {
            return base.Channel.GetNearbyHotels(Location);
        }
        
        public System.Threading.Tasks.Task<GUI.FlightHotelServiceReference.Hotel[]> GetNearbyHotelsAsync(string Location) {
            return base.Channel.GetNearbyHotelsAsync(Location);
        }
    }
}
